package com.example.data.repository

import android.util.Log
import com.example.BuildConfig
import com.example.data.model.*
import com.example.data.remote.RetrofitClient
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class GeminiRepository {
    private val apiKey: String
        get() = try {
            BuildConfig.GEMINI_API_KEY
        } catch (e: Exception) {
            ""
        }

    suspend fun generateWithHighThinking(prompt: String, systemInstruction: String? = null): Result<String> = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Result.failure(Exception("Gemini API key is not configured. Please add GEMINI_API_KEY to AI Studio Secrets panel."))
        }
        try {
            val request = GeminiGenerateRequest(
                contents = listOf(
                    GeminiContent(
                        role = "user",
                        parts = listOf(GeminiPart(text = prompt))
                    )
                ),
                generationConfig = GeminiGenerationConfig(
                    thinkingConfig = GeminiThinkingConfig(thinkingLevel = "high")
                ),
                systemInstruction = systemInstruction?.let {
                    GeminiContent(parts = listOf(GeminiPart(text = it)))
                }
            )
            val response = RetrofitClient.geminiService.generateContent("gemini-3.1-pro-preview", apiKey, request)
            val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No response generated by gemini-3.1-pro-preview."
            Result.success(text)
        } catch (e: Exception) {
            Log.e("GeminiRepository", "High Thinking error: ${e.message}", e)
            Result.failure(e)
        }
    }

    suspend fun generateFast(prompt: String, systemInstruction: String? = null): Result<String> = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Result.failure(Exception("Gemini API key is not configured. Please add GEMINI_API_KEY to AI Studio Secrets panel."))
        }
        try {
            val request = GeminiGenerateRequest(
                contents = listOf(
                    GeminiContent(
                        role = "user",
                        parts = listOf(GeminiPart(text = prompt))
                    )
                ),
                systemInstruction = systemInstruction?.let {
                    GeminiContent(parts = listOf(GeminiPart(text = it)))
                }
            )
            val response = RetrofitClient.geminiService.generateContent("gemini-3.1-flash-lite", apiKey, request)
            val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No response generated by gemini-3.1-flash-lite."
            Result.success(text)
        } catch (e: Exception) {
            Log.e("GeminiRepository", "Fast Flash-Lite error: ${e.message}", e)
            Result.failure(e)
        }
    }

    suspend fun generateWithSearch(prompt: String): Result<String> = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Result.failure(Exception("Gemini API key is not configured. Please add GEMINI_API_KEY to AI Studio Secrets panel."))
        }
        try {
            val request = GeminiGenerateRequest(
                contents = listOf(
                    GeminiContent(
                        role = "user",
                        parts = listOf(GeminiPart(text = prompt))
                    )
                ),
                tools = listOf(mapOf("googleSearch" to emptyMap<String, Any>()))
            )
            val response = RetrofitClient.geminiService.generateContent("gemini-3.5-flash", apiKey, request)
            val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No search-grounded response received."
            Result.success(text)
        } catch (e: Exception) {
            Log.e("GeminiRepository", "Search Grounding error: ${e.message}", e)
            Result.failure(e)
        }
    }

    suspend fun generateWithMaps(prompt: String): Result<String> = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Result.failure(Exception("Gemini API key is not configured. Please add GEMINI_API_KEY to AI Studio Secrets panel."))
        }
        try {
            val request = GeminiGenerateRequest(
                contents = listOf(
                    GeminiContent(
                        role = "user",
                        parts = listOf(GeminiPart(text = prompt))
                    )
                ),
                tools = listOf(mapOf("googleMaps" to emptyMap<String, Any>()))
            )
            val response = RetrofitClient.geminiService.generateContent("gemini-3.5-flash", apiKey, request)
            val text = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No maps-grounded response received."
            Result.success(text)
        } catch (e: Exception) {
            Log.e("GeminiRepository", "Maps Grounding error: ${e.message}", e)
            Result.failure(e)
        }
    }

    suspend fun generateImage(prompt: String, imageSize: String = "1K"): Result<String> = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Result.failure(Exception("Gemini API key is not configured. Please add GEMINI_API_KEY to AI Studio Secrets panel."))
        }
        try {
            val request = GeminiGenerateRequest(
                contents = listOf(
                    GeminiContent(
                        role = "user",
                        parts = listOf(GeminiPart(text = prompt))
                    )
                ),
                generationConfig = GeminiGenerationConfig(
                    imageConfig = GeminiImageConfig(aspectRatio = "1:1", imageSize = imageSize),
                    responseModalities = listOf("TEXT", "IMAGE")
                )
            )
            val response = RetrofitClient.geminiService.generateContent("gemini-3-pro-image-preview", apiKey, request)
            val candidate = response.candidates?.firstOrNull()
            val textPart = candidate?.content?.parts?.firstOrNull { it.text != null }?.text ?: ""
            val imagePart = candidate?.content?.parts?.firstOrNull { it.inlineData != null }
            if (imagePart?.inlineData != null) {
                Result.success("data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}")
            } else {
                Result.success(textPart.ifBlank { "Image generation request processed." })
            }
        } catch (e: Exception) {
            Log.e("GeminiRepository", "Image Generation error: ${e.message}", e)
            Result.failure(e)
        }
    }

    suspend fun generateTTS(text: String): Result<String> = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Result.failure(Exception("Gemini API key is not configured. Please add GEMINI_API_KEY to AI Studio Secrets panel."))
        }
        try {
            val request = GeminiGenerateRequest(
                contents = listOf(
                    GeminiContent(
                        role = "user",
                        parts = listOf(GeminiPart(text = text))
                    )
                ),
                generationConfig = GeminiGenerationConfig(
                    responseModalities = listOf("AUDIO"),
                    speechConfig = GeminiSpeechConfig(
                        voiceConfig = GeminiVoiceConfig(
                            prebuiltVoiceConfig = GeminiPrebuiltVoiceConfig(voiceName = "Kore")
                        )
                    )
                )
            )
            val response = RetrofitClient.geminiService.generateContent("gemini-3.8-flash-tts", apiKey, request)
            val audioData = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull { it.inlineData != null }?.inlineData?.data
            if (audioData != null) {
                Result.success(audioData)
            } else {
                Result.success("Speech generated successfully.")
            }
        } catch (e: Exception) {
            Log.e("GeminiRepository", "TTS error: ${e.message}", e)
            Result.failure(e)
        }
    }
}
